/** URLs honor Vite's configured deployment base. Files are independent. */
const base = import.meta.env.BASE_URL + 'assets/mehewara/';
export const mehewaraAssets = {
  mehewaraLogoPrimary: base + 'mehewara-logo-primary.svg',
  mehewaraLogoWhite: base + 'mehewara-logo-white.svg',
  mehewaraLogoIcon: base + 'mehewara-logo-icon.svg',
  mehewaraLogoCompact: base + 'mehewara-logo-compact.svg',
  mehewaraWelcomeBg: base + 'mehewara-welcome-bg.webp',
  mehewaraWelcomeLeaves: base + 'mehewara-welcome-leaves.svg',
  mehewaraWelcomeCityscape: base + 'mehewara-welcome-cityscape.svg',
  mehewaraWelcomeDecoration: base + 'mehewara-welcome-decoration.svg',
  mehewaraLeafDecoration: base + 'mehewara-leaf-decoration.svg',
  mehewaraWavePattern: base + 'mehewara-wave-pattern.svg',
  mehewaraDotPattern: base + 'mehewara-dot-pattern.svg',
  mehewaraCircleAccent: base + 'mehewara-circle-accent.svg',
  mehewaraLineAccent: base + 'mehewara-line-accent.svg',
  problemDrainage: base + 'problem-drainage.webp',
  problemRoadPothole: base + 'problem-road-pothole.webp',
  problemWaste: base + 'problem-waste.webp',
  problemStreetlight: base + 'problem-streetlight.webp',
  problemEnvironment: base + 'problem-environment.webp',
  problemOverflowDrain: base + 'problem-overflow-drain.webp',
  problemRoadDamage: base + 'problem-road-damage.webp',
  problemBusStopWaste: base + 'problem-bus-stop-waste.webp',
  emptyNoProblems: base + 'empty-no-problems.svg',
  emptyNoResults: base + 'empty-no-results.svg',
  emptyError: base + 'empty-error.svg',
  iconDrainage: base + 'icon-drainage.svg',
  iconRoad: base + 'icon-road.svg',
  iconWaste: base + 'icon-waste.svg',
  iconElectrical: base + 'icon-electrical.svg',
  iconEnvironment: base + 'icon-environment.svg',
  iconDashboard: base + 'icon-dashboard.svg',
  iconReports: base + 'icon-reports.svg',
  iconProblems: base + 'icon-problems.svg',
  iconWorkOrders: base + 'icon-work-orders.svg',
  iconMap: base + 'icon-map.svg',
  iconAnalytics: base + 'icon-analytics.svg',
  iconUsers: base + 'icon-users.svg',
  iconSettings: base + 'icon-settings.svg',
  iconSearch: base + 'icon-search.svg',
  iconFilter: base + 'icon-filter.svg',
  iconLocation: base + 'icon-location.svg',
  iconCalendar: base + 'icon-calendar.svg',
  iconDocument: base + 'icon-document.svg',
  iconArrowRight: base + 'icon-arrow-right.svg',
  iconArrowLeft: base + 'icon-arrow-left.svg',
  iconChevronDown: base + 'icon-chevron-down.svg',
  iconBell: base + 'icon-bell.svg',
  iconUser: base + 'icon-user.svg',
  iconRefresh: base + 'icon-refresh.svg',
  iconWarning: base + 'icon-warning.svg',
  iconInfo: base + 'icon-info.svg',
  iconClose: base + 'icon-close.svg',
  iconGrid: base + 'icon-grid.svg',
  iconList: base + 'icon-list.svg',
  priorityCritical: base + 'priority-critical.svg',
  priorityHigh: base + 'priority-high.svg',
  priorityMedium: base + 'priority-medium.svg',
  priorityLow: base + 'priority-low.svg',
  statusIdentified: base + 'status-identified.svg',
  statusAssigned: base + 'status-assigned.svg',
  statusInProgress: base + 'status-in-progress.svg',
  statusResolved: base + 'status-resolved.svg',
  mehewaraSidebarBg: base + 'mehewara-sidebar-bg.webp',
} as const;
export const problemImageAlt = {
  "problemDrainage": "Blocked roadside drainage grate with leaves and wet pavement.",
  "problemRoadPothole": "Large pothole with crumbling asphalt edges on a municipal road.",
  "problemWaste": "Garbage bags and litter accumulated beside a leafy roadside.",
  "problemStreetlight": "Illuminated municipal streetlight over a quiet road at dusk.",
  "problemEnvironment": "Fallen leafy branch obstructing a paved pedestrian pathway.",
  "problemOverflowDrain": "Water overflowing a clogged curb drain onto the roadside.",
  "problemRoadDamage": "Network of cracks and damaged patches in an asphalt road.",
  "problemBusStopWaste": "Garbage bags and litter beside an empty municipal bus shelter."
} as const;
