// <auto-generated />
using System;
using Mehewara.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mehewara.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mehewara.API.Models.ApprovalHistory", b =>
                {
                    b.Property<Guid>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("approval_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("ApprovalId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_approval_history_created_at");

                    b.HasIndex("DecidedBy")
                        .HasDatabaseName("idx_approval_history_decided_by");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("idx_approval_history_work_order_id");

                    b.ToTable("approval_history", null, t =>
                        {
                            t.HasCheckConstraint("chk_approval_history_decision", "\"decision\" IN ('APPROVED', 'REJECTED', 'REVISION_REQUIRED')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.Crew", b =>
                {
                    b.Property<Guid>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crew_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CrewLeaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("crew_leader_user_id");

                    b.Property<string>("CrewName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("crew_name");

                    b.Property<string>("CrewType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("crew_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("AVAILABLE")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CrewId");

                    b.HasIndex("CrewLeaderUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_crews_leader");

                    b.HasIndex("CrewName")
                        .IsUnique();

                    b.HasIndex("CrewType")
                        .HasDatabaseName("idx_crews_type");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_crews_status");

                    b.ToTable("crews", null, t =>
                        {
                            t.HasCheckConstraint("chk_crews_status", "\"status\" IN ('AVAILABLE', 'BUSY', 'UNAVAILABLE')");

                            t.HasCheckConstraint("chk_crews_type", "\"crew_type\" IN ('DRAINAGE', 'ROAD', 'WASTE', 'ELECTRICAL', 'ENVIRONMENT')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.Problem", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<int?>("PriorityScore")
                        .HasColumnType("integer")
                        .HasColumnName("priority_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("IDENTIFIED")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ProblemId");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_problems_category");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_problems_priority");

                    b.HasIndex("PriorityScore")
                        .HasDatabaseName("idx_problems_priority_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_problems_status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_problems_location");

                    b.ToTable("problems", null, t =>
                        {
                            t.HasCheckConstraint("chk_problems_category", "\"category\" IN ('DRAINAGE', 'ROAD', 'WASTE', 'ELECTRICAL', 'ENVIRONMENT')");

                            t.HasCheckConstraint("chk_problems_latitude", "\"latitude\" >= -90 AND \"latitude\" <= 90");

                            t.HasCheckConstraint("chk_problems_longitude", "\"longitude\" >= -180 AND \"longitude\" <= 180");

                            t.HasCheckConstraint("chk_problems_priority", "\"priority\" IS NULL OR \"priority\" IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("chk_problems_priority_score", "\"priority_score\" IS NULL OR (\"priority_score\" >= 0 AND \"priority_score\" <= 100)");

                            t.HasCheckConstraint("chk_problems_status", "\"status\" IN ('IDENTIFIED', 'AWAITING_ASSIGNMENT', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("resident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ReportId");

                    b.HasIndex("Category")
                        .HasDatabaseName("idx_reports_category");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_reports_created_at");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("idx_reports_problem_id");

                    b.HasIndex("ResidentId")
                        .HasDatabaseName("idx_reports_resident_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_reports_status");

                    b.HasIndex("Latitude", "Longitude")
                        .HasDatabaseName("idx_reports_location");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("chk_reports_category", "\"category\" IN ('DRAINAGE', 'ROAD', 'WASTE', 'ELECTRICAL', 'ENVIRONMENT')");

                            t.HasCheckConstraint("chk_reports_latitude", "\"latitude\" >= -90 AND \"latitude\" <= 90");

                            t.HasCheckConstraint("chk_reports_longitude", "\"longitude\" >= -180 AND \"longitude\" <= 180");

                            t.HasCheckConstraint("chk_reports_status", "\"status\" IN ('PENDING', 'PROCESSING', 'ASSIGNED', 'RESOLVED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.ReportPhoto", b =>
                {
                    b.Property<Guid>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PhotoId");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("idx_report_photos_report_id");

                    b.ToTable("report_photos", (string)null);
                });

            modelBuilder.Entity("Mehewara.API.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("role_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Mehewara.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_users_active");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("idx_users_role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("text")
                        .HasColumnName("completion_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid")
                        .HasColumnName("crew_id");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PENDING_APPROVAL")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_work_orders_created_at");

                    b.HasIndex("CrewId")
                        .HasDatabaseName("idx_work_orders_crew_id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_work_orders_priority");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("idx_work_orders_problem_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_work_orders_status");

                    b.ToTable("work_orders", null, t =>
                        {
                            t.HasCheckConstraint("chk_work_orders_priority", "\"priority\" IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");

                            t.HasCheckConstraint("chk_work_orders_status", "\"status\" IN ('PENDING_APPROVAL', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkflowEvent", b =>
                {
                    b.Property<Guid>("WorkflowEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_event_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_name");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputData")
                        .HasColumnType("jsonb")
                        .HasColumnName("input_data");

                    b.Property<string>("OutputData")
                        .HasColumnType("jsonb")
                        .HasColumnName("output_data");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("ToolResults")
                        .HasColumnType("jsonb")
                        .HasColumnName("tool_results");

                    b.Property<string>("ValidationResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_result");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id");

                    b.HasKey("WorkflowEventId");

                    b.HasIndex("AgentName")
                        .HasDatabaseName("idx_workflow_events_agent_name");

                    b.HasIndex("Stage")
                        .HasDatabaseName("idx_workflow_events_stage");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_workflow_events_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_workflow_events_status");

                    b.HasIndex("WorkflowRunId")
                        .HasDatabaseName("idx_workflow_events_workflow_run_id");

                    b.ToTable("workflow_events", null, t =>
                        {
                            t.HasCheckConstraint("chk_workflow_events_stage", "\"stage\" IN ('REPORT_ANALYSIS', 'PROBLEM_CONSOLIDATION', 'PRIORITIZATION', 'VALIDATION', 'WAITING_FOR_APPROVAL', 'WORK_EXECUTION', 'COMPLETED')");

                            t.HasCheckConstraint("chk_workflow_events_status", "\"status\" IN ('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'WAITING')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkflowRun", b =>
                {
                    b.Property<Guid>("WorkflowRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_run_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_stage");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("StateData")
                        .HasColumnType("jsonb")
                        .HasColumnName("state_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("RUNNING")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("WorkflowRunId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_workflow_runs_created_at");

                    b.HasIndex("CurrentStage")
                        .HasDatabaseName("idx_workflow_runs_current_stage");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("idx_workflow_runs_problem_id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("idx_workflow_runs_report_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_workflow_runs_status");

                    b.ToTable("workflow_runs", null, t =>
                        {
                            t.HasCheckConstraint("chk_workflow_runs_stage", "\"current_stage\" IN ('REPORT_ANALYSIS', 'PROBLEM_CONSOLIDATION', 'PRIORITIZATION', 'VALIDATION', 'WAITING_FOR_APPROVAL', 'WORK_EXECUTION', 'COMPLETED')");

                            t.HasCheckConstraint("chk_workflow_runs_status", "\"status\" IN ('RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("Mehewara.API.Models.ApprovalHistory", b =>
                {
                    b.HasOne("Mehewara.API.Models.User", "DecidedByUser")
                        .WithMany()
                        .HasForeignKey("DecidedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mehewara.API.Models.WorkOrder", "WorkOrder")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecidedByUser");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Mehewara.API.Models.Crew", b =>
                {
                    b.HasOne("Mehewara.API.Models.User", "CrewLeaderUser")
                        .WithMany()
                        .HasForeignKey("CrewLeaderUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CrewLeaderUser");
                });

            modelBuilder.Entity("Mehewara.API.Models.Report", b =>
                {
                    b.HasOne("Mehewara.API.Models.Problem", "Problem")
                        .WithMany("Reports")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mehewara.API.Models.User", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("Mehewara.API.Models.ReportPhoto", b =>
                {
                    b.HasOne("Mehewara.API.Models.Report", "Report")
                        .WithMany("Photos")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Mehewara.API.Models.User", b =>
                {
                    b.HasOne("Mehewara.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkOrder", b =>
                {
                    b.HasOne("Mehewara.API.Models.Crew", "Crew")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mehewara.API.Models.Problem", "Problem")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkflowEvent", b =>
                {
                    b.HasOne("Mehewara.API.Models.WorkflowRun", "WorkflowRun")
                        .WithMany("WorkflowEvents")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkflowRun", b =>
                {
                    b.HasOne("Mehewara.API.Models.Problem", "Problem")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mehewara.API.Models.Report", "Report")
                        .WithMany("WorkflowRuns")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Mehewara.API.Models.Crew", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Mehewara.API.Models.Problem", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("WorkOrders");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("Mehewara.API.Models.Report", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("WorkflowRuns");
                });

            modelBuilder.Entity("Mehewara.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkOrder", b =>
                {
                    b.Navigation("ApprovalHistories");
                });

            modelBuilder.Entity("Mehewara.API.Models.WorkflowRun", b =>
                {
                    b.Navigation("WorkflowEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
